import {NgModule} from '@angular/core';
import {
    MatAutocompleteModule, MatDialogModule, MatSlideToggleModule, MatTooltipModule, MatSnackBarModule,
    MatCardModule, MatToolbarModule, MatIconModule, MatSelectModule, MatInputModule, MatButtonModule,
    MatCheckboxModule, MatChipsModule, MatFormFieldModule, MatStepperModule, MatButtonToggleModule, MatExpansionModule,
    MatMenuModule, MatSidenavModule, MatTabsModule, MatRippleModule, MatProgressBarModule, MatDatepickerModule,
    MatNativeDateModule, MatTableModule
} from '@angular/material';

@NgModule({
    imports: [MatButtonModule,
        MatCheckboxModule,
        MatSelectModule,
        MatSnackBarModule,
        MatChipsModule,
        MatDialogModule,
        MatInputModule,
        MatFormFieldModule,
        MatStepperModule,
        MatTooltipModule,
        MatIconModule,
        MatButtonToggleModule,
        MatCardModule,
        MatExpansionModule,
        MatMenuModule,
        MatSidenavModule,
        MatToolbarModule,
        MatTabsModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSlideToggleModule,
        MatExpansionModule,
        MatRippleModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatTableModule],
    exports: [MatButtonModule,
        MatCheckboxModule,
        MatSelectModule,
        MatSnackBarModule,
        MatChipsModule,
        MatDialogModule,
        MatInputModule,
        MatFormFieldModule,
        MatStepperModule,
        MatTooltipModule,
        MatIconModule,
        MatButtonToggleModule,
        MatCardModule,
        MatExpansionModule,
        MatMenuModule,
        MatSidenavModule,
        MatToolbarModule,
        MatTabsModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSlideToggleModule,
        MatExpansionModule,
        MatRippleModule,
        MatProgressBarModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatTableModule]
})
export class MaterialModule {}